title: Xenos' Blog                            # The title of the blog
author: xenosiakovos                         # Your name
email: xenosiakovos2003@gmail.com               # your email shown in the footer
url: https://xenosiakovos.github.io   # this is your site's root address.
description: > # this means to ignore newlines until "show_excerpts:"
  A clean and minimalist theme for Jekyll.
favicon: "./favicon.ico"     # set the favicon of the site

show_excerpts: false # set to true to show excerpts on the homepage
permalink: /:title/
related: true       # set to true to show related posts at the end of a post
show-tags: true     # set to true to show tags at the end of a post

# Moving date format
# refer to https://shopify.github.io/liquid/filters/date/ if you want to customize this
arreando:
  avatar_url: "/assets/images/profile.jpg"  # avatar in about page
                                            # header image is in /assets/css/header.jpg
  about_you: a short description about you. # short description about you in about page
  date_format: "%b %d"                      # date format of posts in home page
  back_to: "blog"                           # In the post page, you have a back button above the title, you can custom the text by yourself.

  # generate social links in about page.
  social_links:
    # twitter: jartigag
    github:  xenosiakovos
    rss: RSS
    # facebook:
    # flickr:
     instagram: xenosiakovos
    # linkedin:
    # pinterest:
    # youtube:
    # youtube_channel:
    # youtube_channel_name:
    # telegram:
    # googleplus:
    # reddit:

    # Mastodon instances
    # mastodon:
    # - username:
    #   instance:
    # - username:
    #   instance:

# Build settings
remothe_theme: jartigag/arreando # note, please use jartigag/arreando if you want to publish to Github Pages.

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-redirect-from
